### ISSUE TITLE
HW source

### ISSUE THREAD

**Issue by pilotak** [TheStaticTurtle/Open433#1]
Hi,
first of all nice project, i wanted to do the same. Would you be willing to share a source of PCB? only gerber appears to be uploaded. I can also see a schematic but in JSON format - what was the program you created it in? It would be nice to share a PDF schematic

**Comment by TheStaticTurtle** [comment]
Just uploaded it now, I use EasyEDA as an editor this is where the json format came from. I also exported pdf / dxf / altium files

**Comment by pilotak** [comment]
Thanks a lot.

@TheStaticTurtle You wrote on the blog that you tried a RF switch. Which one did you use? because i need to use only one SMA antenna

**Comment by TheStaticTurtle** [comment]
I was using an HMC544AE but if I had to guess I think it would be more my shitty soldering / wiring that made it non-functional

**Comment by pilotak** [comment]
OK, i was thinking about following which are basically the same as Analog
- AS213-92LF
- CG2179M2-C4
- MASWSS0115TR-3000

Yes they have a tiny footprint but have at least pins as oppose to pads at the bottom totally unusable for home soldering

**Comment by TheStaticTurtle** [comment]
Just some information the AS213-92LF has a 1.8 control voltage the other ones are fine with 5v but don't be like and forget the caps at the input / output

**Comment by pilotak** [comment]
Datasheet says that it can be 1.8-5V. Thanks for the caps tip.

One more question did you use one output pin on arduino to control the switch (A+B tied together) or two separate pins

**Comment by TheStaticTurtle** [comment]
Well you need two pins since one will control input A and the other B if you tie them together it will just not work (that's probably what happened to me)
