### ISSUE TITLE
Frequency?

### ISSUE THREAD

**Issue by atrent** [TheStaticTurtle/Open433#2]
Is it a 433.92 MHz standard?
If so would it be possible to support the 433.42 MHz standard? (e.g. Somfy)
Thanks

**Comment by TheStaticTurtle** [comment]
All the frequencies / protocol working for the rc-switch library is compatible with this software (e.g. 315/433MHz), the receivers are usually wide enough to cover both the frequency you mentioned, if it isn't the case you can simply use ones that are compatible or change the quartz.

However, you still need the protocol. From what I can remember, somfy uses rolling codes which makes it much harder / impossible to control the device without the rolling algorithm. 
However, I've just seen that the Somfy RTS or Simu HZ remote protocol have been reverse engineered so it might be possible. But I don't have the time right now

With a bit (lot) of work it would be possible to implement a multi-remote system with the correct rolling code for each one, here's documentation:
https://github.com/Nickduino/Somfy_Remote
https://pushstack.wordpress.com/somfy-rts-protocol/
